### ISSUE TITLE
[Bug] Failing peer results in "failed to load wallet data"

### ISSUE THREAD

**Issue by arkmoon** [dated/transaction-export-plugin#2]
I noticed this awhile back, and now there's a Reddit post indicating the same bug:
https://www.reddit.com/r/ArkEcosystem/comments/s2b5lf/reinstall_ark_transaction_export_plugin/

There are two instances of a Promise.all() where if the user happens to have a bad peer in their list, results in the failure: **"failed to load wallet data"** and even reloading the desktop wallet or refreshing the peer list doesn't seem to fix it.

- src/pages/index.js: Line 733
- src/services/market.service.js: Line 73

Something to consider, pinging a peer before attempting to use it, and if it fails have some sort of fallback mechanism to find a new peer.

**Comment by dated** [comment]
Thanks for bringing this to my attention @arkmoon, it should be fixed with 6fdaa6001ce5188366be7dfae94d45659daf99f4 and released as `1.1.5`. Besides of the problem with `Promise.all` which was replaced with `Promise.allSettled` where appropriate, i think the plugin didn't properly handle peers whose Core API was configured, while having the respective port closed.

**Comment by dated** [comment]
Some more adjustments were made in ed94e5ebfb5ba58f0d6e389667572e8ced3a6191 and eb1c0fbb8b11176d71267f002d31c1671374c911 to reduce the number of requests made and to filter out to pick the right peers. This will be available as `1.1.6` shortly.
